# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dab28ecc09a94578b2023e3ccf972ae67dcf46d2e949275f5f8d9b3d6c31bb76344ae56d39899901900fb60daf7c8674d4ffbf99217a5d0805f4ba2b098796d0

test:
  secret_key_base: ed8f83256122168677aebc77a586b5300b317fd421840daa7572ba8936085156f3595119e2fc5a4afe75fc408cf5c19825b08c93b63975492b89113e090bffca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
